### PR TITLE
Replace Make with CMake

### PR DESCRIPTION
**Pull request by yeah-its-gloria**
This pull request replaces Make with CMake.
It also separates the test application, thus allowing it to be built separately if needed.
On top of all that, this'll makes it possible to build nxjson on Windows via MSVC/Visual Studio without having to install outside tools.

### CODE REVIEW

**Comment by yarosla** [comment]
Hi Marko,

Could you please add section "How to Build" to README.md (right before "Usage Example") with instructions on how to build library and run tests.

Yaroslav

**Comment by yeah-its-gloria** [comment]
I added the build instructions, let me know if something is unclear.

**Comment by yarosla** [comment]
I have cmake version 3.7.2 (from Debian 9 repo).

What I did:

```
[~/dev/nb/nxjson/build]% cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON
CMake Error at CMakeLists.txt:15 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "nxjson".

-- Configuring incomplete, errors occurred!
See also "/home/ys/dev/nb/nxjson/build/CMakeFiles/CMakeOutput.log".
```

I've changed (not sure it'll behave on Windows):

```
install(TARGETS nxjson
        ARCHIVE DESTINATION lib)

```

Then I did:
```
[~/dev/nb/nxjson/build]% cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ys/dev/nb/nxjson/build
[~/dev/nb/nxjson/build]% cmake --build . --config Release
Scanning dependencies of target nxjson
[ 50%] Building C object CMakeFiles/nxjson.dir/nxjson.c.o
[100%] Linking C static library libnxjson.a
[100%] Built target nxjson
```

It did build libnxjson.a but I do not see test binary nxjson-test anywhere. Neither the tests output.

I am not confident CMake user so I need your help to properly set it up.

**Comment by yeah-its-gloria** [comment]
Turns out I wrote "BUILD_TESTS" instead of "BUILD_TEST", whoops. Going to fix that ASAP!
I'll add your change to the CMakeLists.txt file (it works on Windows too) as well.

**Comment by yeah-its-gloria** [comment]
That's it! It'll also copy the test binary and its tests (if built) to the install path now.
The test binary will reside under `bin` and the test files under `share`.

Also; apologies for being so late.

**Comment by yarosla** [comment]
I'm also not very quick. Have time on weekends only.

Here is what works for me:
```
cmake -E make_directory build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TEST=ON
cmake --build . --config Release
cd test
./nxjson-test
```

Could you please check if this works for you. It would be better to have single set of instructions for all versions of cmake and across platforms.

I borrowed these commands from GitHub Actions for cmake sample. Mentioned there is also `ctest`, which would be really nice to adopt together with `cmake` (instead of my homegrown testing approach). I can do it later on myself, or you can do it if you like.

And I don't think we need to install test binary.

**Comment by yeah-its-gloria** [comment]
Yeah, that works for me too, but yours is a bit more convoluted.
I can just do
```sh
cmake -B build
cmake --build build --config Debug # or any other configuration
```
and that's it.
I'll remove the test binary from the CMakeLists; I'll let you handle CTest.

**Comment by yarosla** [comment]
Thanks for the contribution!

**Comment by yarosla** [comment]
Could you please check my latest changes. Changed default for BUILD_TEST to ON. Added `ctest` and set up GitHub build pipeline.

**Comment by yeah-its-gloria** [comment]
Running `ctest -C Debug --verbose` tells me that no test could be found.
Also; I get a ton of warnings from the compiler:
This one is from nxjson itself:
```
nxjson\nxjson.c(300,40): warning C4244: '=': conversion from '__int64' to 'double', possible loss of data [nxjson\build\nxjson.vcxproj]
```

These ones originate from the test program:
```
nxjson\test\test.c(39,14): warning C4013: 'open' undefined; assuming extern returning int [nxjson\build\test\nxjson-test.vcxproj]
nxjson\test\test.c(45,23): warning C4013: 'read' undefined; assuming extern returning int [nxjson\build\test\nxjson-test.vcxproj]
nxjson\test\test.c(47,10): warning C4013: 'close' undefined; assuming extern returning int [nxjson\build\test\nxjson-test.vcxproj]
nxjson\test\test.c(62,20): warning C4013: 'write' undefined; assuming extern returning int [nxjson\build\test\nxjson-test.vcxproj]
nxjson\test\test.c(61,1): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [nxjson\build\test\nxjson-test.vcxproj]
nxjson\test\test.c(79,5): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [nxjson\build\test\nxjson-test.vcxproj]
nxjson\test\test.c(85,7): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [nxjson\build\test\nxjson-test.vcxproj]
nxjson\test\test.c(114,7): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [nxjson\build\test\nxjson-test.vcxproj]
nxjson\test\test.c(119,12): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [nxjson\build\test\nxjson-test.vcxproj]
nxjson\test\test.c(122,12): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [nxjson\build\test\nxjson-test.vcxproj]
nxjson\test\test.c(128,7): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [nxjson\build\test\nxjson-test.vcxproj]
nxjson\test\test.c(137,1): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [nxjson\build\test\nxjson-test.vcxproj]
nxjson\test\test.c(156,3): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [nxjson\build\test\nxjson-test.vcxproj]
nxjson\test\test.c(181,5): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [nxjson\build\test\nxjson-test.vcxproj]
nxjson\test\test.c(182,5): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [nxjson\build\test\nxjson-test.vcxproj]
```
I'd highly suggest following the advice from the warnings regarding the unsafe functions.

Side note; you might want to add this to `nxjson.h`:
```c
#if defined(_WIN32)
#define NX_JSON_EXPORT __declspec(dllexport)
#elif defined(__GNUC__) || defined(COMPILER_GCC) || defined(__APPLE__)
#define NX_JSON_EXPORT __attribute__((visibility("default")))
#else
#error "Unsupported Platform"
#endif
```
After that, you'll then append this to every function, using `nx_json_parse` as an example:
```c
NX_JSON_EXPORT const nx_json* nx_json_parse(char* text, nx_json_unicode_encoder encoder);
```
In case someone would build nxjson as a shared library, this would export the symbols and allow them to be used via that DLL/dylib/so/whatever that OS might use.
All that'll be necessary then would be to add this around the `add_library` statement in `CMakeLists.txt`:
```cmake
# ...
option(BUILD_SHARED "Builds nxjson as a shared library." OFF)

if(BUILD_SHARED)
    set(BUILD_MODE SHARED)
else()
    set(BUILD_MODE STATIC)
endif()

add_library(nxjson ${BUILD_MODE}
# ...
```

**Comment by yarosla** [comment]
> Running ctest -C Debug --verbose tells me that no test could be found.

Did you run it in `build/test` subdirectory?

Regarding the warnings. `gcc` gives only three: https://github.com/yarosla/nxjson/runs/1173237114?check_suite_focus=true (see Build log). `*_s` versions are only available in Microsoft's CRT. As all of the warnings are in `test.c`, and semantically the cases are safe and correct, I would not bother.

**Comment by yeah-its-gloria** [comment]
The tests pass now, thanks for letting me know.
I've never used CTest before so I thought it'd apply to the whole project instead of just the subdirectory.

Regarding the safe functions; GNU and whatnot seem to have, for example, `snprintf` instead of `sprintf_s`, which have the exact same arguments at the same places. You could declare this at the top of the `nxjson.c`:
```c
#ifdef _MSC_VER
#define snprintf sprintf_s
#endif
```
This'll work the same way across those platforms.

**Pull request merged**
